input {
  tcp {
    port => 5000
    codec => json_lines
    type => "tcp-5000"
  }
  udp {
    port => 5000
    codec => json_lines
    type => "udp-5000"
  }
  tcp {
    port => 6000
    codec => json_lines
    type => "tcp-6000"
  }
}

filter {
  # Add your own filters here (grok, mutate, date, etc.)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs_%{[type]}-index-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
